global:
  scrape_interval: 30s #scraping 간격을 1분단위로 설정

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'win_node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9182']

  - job_name: 'win_gpu_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9835']